[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "icpc"
    name = "ICPC/OI"
    url = "/icpc"
    weight = 2

    
# Social Media Configuration


[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/xinyishi01"
    weight = 1

[[social]]
    identifier = "email"
    name = "Email"
    url = "mailto:xinyi_shi@brown.edu"
    weight = 2